# -*- coding: utf-8 -*-
"""codsoft task2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ft7cD1JaT3k-vER0CFkQUktxO2qcwM9b
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,classification_report
from sklearn.neighbors import KNeighborsClassifier

df = pd.read_csv('/content/IRIS.csv')
df

df.head()

df.tail()

df.sample(5)

df.info()

df.describe()

df.isna()

df.isna().sum()

df['species'].value_counts()

sns.pairplot(df, hue ='species')

x=df[['sepal_length','sepal_width','petal_length','petal_width']]
y=df['species']

print(x)
print(y)

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)
x_train

x_test

ML=KNeighborsClassifier(n_neighbors = 10)
ML.fit(x_train,y_train)

x_train_prediction = ML.predict(x_train)
print(x_train_prediction)

print(y_train)

x_test_prediction = ML.predict(x_test)
x_test_prediction

print(y_test)

train_accuracy = accuracy_score(x_train_prediction,y_train)
test_accuracy = accuracy_score(x_test_prediction,y_test)
print("Accuracy score of training dataset ",train_accuracy)
print("Accuracy score of testing dataset",test_accuracy)

print(classification_report(y_train,x_train_prediction))

print(classification_report(y_test,x_test_prediction))

print("write sepal length")
sepal_length = float(input())
print("write sepal width")
sepal_width = float(input())
print("write petal length")
petal_length = float(input())
print("write petal width")
petal_width = float(input())

data = pd.DataFrame({'sepal_length':[sepal_length],'sepal_width':[sepal_width],'petal_length':[petal_length],'petal_width':[petal_width]})
prediction = ML.predict(data)
print("Species is ",prediction[0])